define([
	'Ractive/prototype/add',
	'Ractive/prototype/animate/_animate',
	'Ractive/prototype/detach',
	'Ractive/prototype/find',
	'Ractive/prototype/findAll',
	'Ractive/prototype/findAllComponents',
	'Ractive/prototype/findComponent',
	'Ractive/prototype/fire',
	'Ractive/prototype/get',
	'Ractive/prototype/insert',
	'Ractive/prototype/merge/_merge',
	'Ractive/prototype/observe/_observe',
	'Ractive/prototype/off',
	'Ractive/prototype/on',
	'Ractive/prototype/render',
	'Ractive/prototype/renderHTML',
	'Ractive/prototype/reset',
	'Ractive/prototype/set',
	'Ractive/prototype/subtract',
	'Ractive/prototype/teardown',
	'Ractive/prototype/toHTML',
	'Ractive/prototype/toggle',
	'Ractive/prototype/update',
	'Ractive/prototype/updateModel'
], function (
	add,
	animate,
	detach,
	find,
	findAll,
	findAllComponents,
	findComponent,
	fire,
	get,
	insert,
	merge,
	observe,
	off,
	on,
	render,
	renderHTML,
	reset,
	set,
	subtract,
	teardown,
	toHTML,
	toggle,
	update,
	updateModel
) {

	'use strict';

	return {
		add: add,
		animate: animate,
		detach: detach,
		find: find,
		findAll: findAll,
		findAllComponents: findAllComponents,
		findComponent: findComponent,
		fire: fire,
		get: get,
		insert: insert,
		merge: merge,
		observe: observe,
		off: off,
		on: on,
		render: render,
		renderHTML: renderHTML,
		reset: reset,
		set: set,
		subtract: subtract,
		teardown: teardown,
		toHTML: toHTML,
		toggle: toggle,
		update: update,
		updateModel: updateModel
	};

});
